{{- if .Values.webhook.enabled -}}
{{- if .Values.webhook.certificate.create -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "prometheus-operator.webhookCertificateName" . }}
  labels:
    {{- include "prometheus-operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "prometheus-operator.webhookCertificateSecretName" . }}
  dnsNames:
    - {{ include "prometheus-operator.fullname" . }}
    - {{ include "prometheus-operator.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "prometheus-operator.fullname" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    {{ .Values.webhook.certificate.issuerRef | nindent 4}}
{{- end -}}
{{- end -}}
